version: "3.8"

services:
  spring-restful-api-db:
    container_name: project-ecommerce-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ecommerce-db
    volumes:
      - "./docker-volume:/var/lib/mysql"
